### ISSUE TITLE
Order without tax (VAT excempt) still display tax in MultisafePay

### ISSUE THREAD

**Issue by dennisbuijsgmailcom** [MultiSafepay/Opencart#13] opened 2023-04-04 09:19 UTC
Hi

When I do an order with zero tax (VAT exempt) with my extension EU Vat Compliant, the order payment is good, price without tax.
BUT, when I go to Multisafepay Dashboard and check the transaction details, I see tax displayed.
 
![msp1](https://user-images.githubusercontent.com/6247951/229746913-11a874e4-9d1e-49d6-a246-6702da3fcfcb.png)

![msp2](https://user-images.githubusercontent.com/6247951/229746943-ec52ecfd-7822-4586-a01a-2adb9fbecc4a.png)

**Comment by danielcivit** [comment] 2023-04-04 09:31
Hi @dennisbuijsgmailcom.  Thanks for contact us. 

I assume you are using the patch to extend compatibility of our extension over  EU Vat Compliant, listed here: 
https://docs.multisafepay.com/docs/opencart#checkouts

===

At this moment, is not clear for me if this issue is related with the OpenCart extension, or with the merchant panel and the way the transaction details are being shown in there. 

It seems to me this case is going to require share some sensitive information, (transactions IDs, merchant IDs, etc) to inspect the details of the transaction internally and check if there is an issue in the results. Therefore, I need to  open an internal ticket where we can share in a secure way these details. 

Could you let me know your email address to open this ticket and after that we can continue the conversation in there? Or you can write us an email to support@multisafepay.com

**Comment by dennisbuijsgmailcom** [comment] 2023-04-04 09:51
dennis@emcgsm.nl

**Comment by danielcivit** [comment] 2023-04-14 15:03
I have confirmation the issue is solved via our internal ticket system. Thanks again for your feedback and report this issue to us @dennisbuijsgmailcom.

I am closing this ticket now, but if you have any other issue related, don't hesitate to reopen this thread, or open a new one.

**Closed as completed by danielcivit** 2023-04-14 15:03 UTC
