### ISSUE TITLE
open_basedir restrictions

### ISSUE THREAD

**Issue by huub1972** [MultiSafepay/Opencart#3] opened 2021-08-02 21:15 UTC
Opencart version 3.0.3.7, php 7.4.3
In the latest opencart distro's storage directory must be moved outof the public web directory.
The MSP module seems to use vendor files from that directory and more outside of that?
With open_basedir opened for publicweb and storage directories the module still generates restriction errors.

Warning: file_exists(): open_basedir restriction in effect. File(/var/www/clients/client1/web5/web/system/library/multisafepay/vendor/composer/../../../../../../src/Sdk.php) is not within the allowed path(s): (/var/www/clients/client1/web5/web:/var/www/clients/client1/web5/storage) in /var/www/clients/client1/web5/storage/vendor/composer/ClassLoader.php on line 384

**Comment by danielcivit** [comment] 2021-08-03 14:47
Hello @huub1972.

Thanks for your report. We are going to investigate this to check what is happening. 
Please, could you share your PHP settings through the ticket you have with us with ID 25177.

**Comment by danielcivit** [comment] 2021-08-03 15:56
We have not been able to to reproduce this issue in our own environments, even when:

- We set the same PHP version 7.4.22. 
- Added in open_basedir directive the public directory of the application and the storage directory outside the public root of the server, like it was reported. 
- Using OpenCart version 3.0.3.7 and extension version 3.10.4. 

We are closing this ticket because we received internally your comment that it was not required a solution for this anymore.
However I added to the backlog of this product a new item with low priority, to check in depth if this could be a common problem. 

So far it has not been reported by anyone else. 

Once again, thanks for your report @huub1972

**Closed as completed by danielcivit** 2021-08-03 15:56 UTC
